name: Build Application (Console Version - Reliable)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., 0.9.0)'
        required: true
        default: '0.9.0'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies (Console)
      run: dotnet restore CricutStencilMaker.Console.csproj
      
    - name: Build console application
      run: dotnet build CricutStencilMaker.Console.csproj -c Release --no-restore
      
    - name: Publish self-contained application
      run: dotnet publish CricutStencilMaker.Console.csproj -c Release --self-contained true -r win-x64 -o "publish/win-x64"
      
    - name: Create portable ZIP
      run: |
        $version = "${{ github.event.inputs.version }}"
        Compress-Archive -Path "publish/win-x64/*" -DestinationPath "CricutStencilMaker-v$version-Console.zip"
        Write-Host "✅ Console version created: CricutStencilMaker-v$version-Console.zip"
        Get-Item "CricutStencilMaker-v$version-Console.zip" | Select-Object Name, Length
      shell: powershell
      
    - name: Upload console version
      uses: actions/upload-artifact@v4
      with:
        name: CricutStencilMaker-Console-v${{ github.event.inputs.version }}
        path: CricutStencilMaker-v${{ github.event.inputs.version }}-Console.zip
        
    - name: Show next steps
      run: |
        Write-Host "🎉 Build completed successfully!" -ForegroundColor Green
        Write-Host ""
        Write-Host "📦 Downloads available:" -ForegroundColor Cyan
        Write-Host "   - Portable ZIP: CricutStencilMaker-v${{ github.event.inputs.version }}-Portable.zip"
        Write-Host ""
        Write-Host "🚀 To create a release:" -ForegroundColor Yellow
        Write-Host "   1. Go to GitHub Releases"
        Write-Host "   2. Click 'Create new release'"
        Write-Host "   3. Tag: v${{ github.event.inputs.version }}"
        Write-Host "   4. Upload the ZIP file from artifacts"
        Write-Host "   5. Add release notes and publish"
      shell: powershell