name: Build Cricut Stencil Maker

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., 0.9.0)'
        required: true
        default: '0.9.0'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
        
    - name: Build
      run: dotnet build -c Release
      
    - name: Publish
      run: dotnet publish -c Release --self-contained true -r win-x64 -o publish
      
    - name: Create ZIP
      run: |
        Compress-Archive -Path "publish/*" -DestinationPath "CricutStencilMaker-v${{ github.event.inputs.version }}.zip"
        Write-Host "✅ Created: CricutStencilMaker-v${{ github.event.inputs.version }}.zip"
      shell: powershell
      
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: CricutStencilMaker-v${{ github.event.inputs.version }}
        path: CricutStencilMaker-v${{ github.event.inputs.version }}.zip